### ISSUE TITLE
目前没有API 这么对接WHMCS啊？macOS 不能打包

### ISSUE THREAD

**Issue by ilovebamboo** [SmRiley/accelerator#1]
目前没有API 这么对接WHMCS啊？macOS 不能打包
![image](https://user-images.githubusercontent.com/6214084/94876887-8c8dca80-048b-11eb-8f4a-aedff8901618.png)

**Comment by ilovebamboo** [comment]
![image](https://user-images.githubusercontent.com/6214084/94877145-4ab15400-048c-11eb-8373-0d78b7748d39.png)

**Comment by SmRiley** [comment]
这api是我写的...既然你想要我看看这两天有没有时间给放上来吧.
另外是winform,Mac是不可能能用的

**Comment by SmRiley** [comment]
API已经提交了,请自测

**Comment by ilovebamboo** [comment]
![image](https://user-images.githubusercontent.com/6214084/94989795-f1d7dd80-05a9-11eb-98d5-ab53b3364844.png)
需要配置这个才能用吗？
![image](https://user-images.githubusercontent.com/6214084/94989802-fa301880-05a9-11eb-85c9-c08c1fd225e1.png)
这个能不能点击选择 某个进程加速，或者全局加速


![image](https://user-images.githubusercontent.com/6214084/94989920-be498300-05aa-11eb-8d13-e8f5b39a767f.png)

token.php?token=&to=cart 这个地址whmcs不支持
![image](https://user-images.githubusercontent.com/6214084/94989996-62cbc500-05ab-11eb-8492-c3c3b75c039a.png)

续费账号没搜到 cart 字符 。
 
我打算给 雷电 网易MUMU 进程加速 
不知道行不行？

**Comment by SmRiley** [comment]
这个加速模块部分我并没有使用netch,当时直接参考的node-tap的全局加速,如果你需要对应的应用,你可能需要自己修改,然后续费的话,去找一个whmcs Renew 模块就行.

**Comment by ilovebamboo** [comment]
我只是尝试安装看看 不支持进程代理 太可惜 用不上，我想弄一个Socks5协议的进程代理。Shadowsocks好像没法和socks5(有用户名密码认证)兼容

**Comment by SmRiley** [comment]
https://www.seeull.com/archives/314.html,参考WFP

> 我只是尝试安装看看 不支持进程代理 太可惜 用不上，我想弄一个Socks5协议的进程代理。Shadowsocks好像没法和socks5(有用户名密码认证)兼容

**Comment by ilovebamboo** [comment]
太复杂完全看不懂啊

**Comment by SmRiley** [comment]
> 太复杂完全看不懂啊

那我就没办法了
